
all: bounds_on_lr_te.html accelerating_online_experiments.html

accelerating_online_experiments.html:  accelerating_online_experiments.xml
	articleml < $< > $@

bounds_on_lr_te.html:  bounds_on_lr_te.xml
	articleml < $< > $@

